### ISSUE TITLE
[FEAT] 테스트 결과 반환 API 구현

### ISSUE THREAD

**Issue by dlrjs2360** [dnd-side-project/dnd-10th-3-backend#1]
## 요구사항

[TEST-3-01] 테스트 결과

## 상세 요구사항

- 사용자가 테스트를 진행하며 입력한 값들을 토대로 결과를 반환합니다.
- 사용자들의 입력값을 데이터베이스에 저장합니다.

## TODO

- [ ] 테스트 결과 저장 스키마 추가
- [ ] 테스트 결과 도출 로직 작성
- [ ] Swagger 명세서 작성
- [ ] Swagger 테스트 진행

## 예상 소요 시간

4시간

## 기타 참고사항

- 아직 테스트 결과 데이터를 어떤 것을 저장할 지 결정해야 합니다.
- 사용자의 이름, 상대방의 이름은 프론트에서 저장하고 있다가 한 번의 요청으로 입력값과 함께 넘겨줘야 합니다.

## ✅ Issue 등록 전 확인 후 체크해 주세요! (x 표시 해 주세요.)

- [x] Assignees(이슈 담당자)를 지정했습니다.
- [x] Labels, Milestone을 등록했습니다.
