### ISSUE TITLE
[FEAT] 투표 공감 API 구현

### ISSUE THREAD

**Issue by dlrjs2360** [dnd-side-project/dnd-10th-3-backend#10]
## 요구사항

[COMM-2-04] 투표 공감 기능

## 상세 요구사항

- 투표에 좋아요를 눌러 공감할 수 있어야 한다.
- 이미 좋아요를 누른 투표를 다시 누르면 취소되어야 한다.
- 사용자마다 한 투표에 한 공감만 가능해야 한다.

## TODO

- [x] 공감 스키마 추가
- [x] 외래키 조건 검토
- [ ] Swagger 명세서 작성
- [ ] Swagger 테스트 진행

## 예상 소요 시간

4시간

## ✅ Issue 등록 전 확인 후 체크해 주세요! (x 표시 해 주세요.)

- [x] Assignees(이슈 담당자)를 지정했습니다.
- [x] Labels, Milestone을 등록했습니다.
