### ISSUE TITLE
[FEAT] 투표 참여 API 구현

### ISSUE THREAD

**Issue by dlrjs2360** [dnd-side-project/dnd-10th-3-backend#11]
## 요구사항

[COMM-2-03] 투표 참여 기능

## 상세 요구사항

- 사용자마다 한 투표에 하나의 선택지를 선택할 수 있다.
- 투표에 참여한 사용자는 선택지를 수정할 수 있다.
- 스레드 안정적으로 구현해야 한다.

## TODO

- [ ] synchronized 사용
- [ ] 이미 투표에 참여했다면 투표를 수정

## 예상 소요 시간

5시간

## 기타 참고사항

- 선택지를 변경할 때 알럿을 띄워서 API 호출 속도가 너무 빠르지 않았으면 좋겠음.

## ✅ Issue 등록 전 확인 후 체크해 주세요! (x 표시 해 주세요.)

- [x] Assignees(이슈 담당자)를 지정했습니다.
- [x] Labels, Milestone을 등록했습니다.
