### ISSUE TITLE
[FEAT] 투표 결과 반환 시 댓글 개수 추가 

### ISSUE THREAD

**Issue by wlshooo** [dnd-side-project/dnd-10th-3-backend#121]
## 요구사항
vote response에 댓글 개수를 파악할 수 있게 추가해달라는 요구사항

[요구사항_ID] 소분류명

## 상세 요구사항
댓글 추가, 삭제 되었을 때 댓글 카운트가 변화되어야 한다.

## TODO

- [x] 투표 엔티티에 댓글 카운터 필드 추가
- [x] 투표 response에 댓글 카운터 필드 추가
- [x] 댓글 생성, 삭제 시 투표의 댓글 카운터 증감

## 예상 소요 시간

1h

## ✅ Issue 등록 전 확인 후 체크해 주세요! (x 표시 해 주세요.)

- [x] Assignees(이슈 담당자)를 지정했습니다.
- [x] Labels, Milestone을 등록했습니다.
