### ISSUE TITLE
[FEAT] 진행한 테스트 목록 조회 API 구현

### ISSUE THREAD

**Issue by wlshooo** [dnd-side-project/dnd-10th-3-backend#14]
## 요구사항

MEM-4-01 진행한 테스트 목록 조회
## 상세 요구사항

진행한 테스트 목록을 확인할 수 있어야 한다.
- 목록의 테스트를 클릭하면 테스트 결과를 확인할 수 있어야 한다.

## TODO

- [ ] 목록 조회 구현
- [ ] 삭제 기능 구현
- [ ]  Swagger 명세서 작성
- [ ]  Swagger 테스트 진행

## 예상 소요 시간

4h
## ✅ Issue 등록 전 확인 후 체크해 주세요! (x 표시 해 주세요.)

- [x] Assignees(이슈 담당자)를 지정했습니다.
- [x] Labels, Milestone을 등록했습니다.
