### ISSUE TITLE
[FEAT] 유저 회원 탈퇴 API 구현

### ISSUE THREAD

**Issue by wlshooo** [dnd-side-project/dnd-10th-3-backend#16]
## 요구사항

MEM-6-02 회원 탈퇴

## 상세 요구사항

회원 탈퇴가 가능해야 한다.

## TODO

- [ ]  회원의 논리적 탈퇴
- [ ]  Swagger 명세서 작성
- [ ]  Swagger 테스트 진행

## 예상 소요 시간

1h
## ✅ Issue 등록 전 확인 후 체크해 주세요! (x 표시 해 주세요.)

- [x] Assignees(이슈 담당자)를 지정했습니다.
- [x] Labels, Milestone을 등록했습니다.
