### ISSUE TITLE
[FEAT] 투표 등록 API 구현

### ISSUE THREAD

**Issue by dlrjs2360** [dnd-side-project/dnd-10th-3-backend#2]
## 요구사항

[COMM-1-01] 투표 등록

## 상세 요구사항

- 투표는 인증된 사용자만 생성할 수 있다.
- 카테고리, 제목, 본문, 선택지, 이미지를 입력받아야 한다.
- 컬럼별로 유효성 검사가 이루어져야 한다.

## TODO

- [ ] 컬럼별 유효성 검사 커스텀 어노테이션 구현
- [ ] 이미지 저장소 S3 연결
- [ ] 투표 - 선택지 - 유저투표 연관관계 검토
- [ ] Swagger 명세서 작성
- [ ] Swagger 테스트 진행

## 예상 소요 시간

6시간

## ✅ Issue 등록 전 확인 후 체크해 주세요! (x 표시 해 주세요.)

- [x] Assignees(이슈 담당자)를 지정했습니다.
- [x] Labels, Milestone을 등록했습니다.
