### ISSUE TITLE
[FEAT] 댓글 삭제 API 구현

### ISSUE THREAD

**Issue by wlshooo** [dnd-side-project/dnd-10th-3-backend#20]
## 요구사항

COMM-3-03 댓글 삭제 기능

## 상세 요구사항
등록한 댓글을 삭제할 수 있어야 한다.
- 삭제는 댓글을 등록한 본인만 가능해야 한다.

## TODO

- [ ]  댓글의 논리적 삭제
- [ ]  Swagger 명세서 작성
- [ ]  Swagger 테스트 진행

## 예상 소요 시간

2h
## ✅ Issue 등록 전 확인 후 체크해 주세요! (x 표시 해 주세요.)

- [x] Assignees(이슈 담당자)를 지정했습니다.
- [x] Labels, Milestone을 등록했습니다.
