### ISSUE TITLE
[FEAT] 테스트 결과 API 구현

### ISSUE THREAD

**Issue by dlrjs2360** [dnd-side-project/dnd-10th-3-backend#23]
## 요구사항

[TEST-3-01] 테스트 시작

## 상세 요구사항

- 사전 질문을 입력받을 수 있어야 한다.
  - 상대이름
  - 사용자 나이
  - 사용자 성별
- 믿음, 애정, 소통 선택지에서 1번을 선택한 개수를 입력받는다.
- 위에서 입력받은 내용을 바탕으로 결과를 도출하여 전달한다.
  - 결과 이미지
  - 온도
  - 지수별 수치
  - 추가 멘트

## TODO

- [ ] 사용자 입력 저장
- [ ] 결과 도출
- [ ] 결과 저장
- [ ] Swagger 명세서 작성
- [ ] Swagger 테스트 진행

## 예상 소요 시간

6H

## ✅ Issue 등록 전 확인 후 체크해 주세요! (x 표시 해 주세요.)

- [x] Assignees(이슈 담당자)를 지정했습니다.
- [x] Labels, Milestone을 등록했습니다.
