### ISSUE TITLE
[FEAT] 테스트 결과 저장 API 구현

### ISSUE THREAD

**Issue by dlrjs2360** [dnd-side-project/dnd-10th-3-backend#24]
## 요구사항

[TEST-3-01] 테스트 결과 조회

## 상세 요구사항

비회원이 테스트 결과 조회 후 회원가입하면 자동으로 결과가 저장되는 로직을 구현하기 위해 테스트 결과를 저장하는 API를 따로 구현합니다.

## TODO

- [ ] 테스트 결과 입력
- [ ] 데이터베이스에 결과 저장

## 예상 소요 시간

3시간

## ✅ Issue 등록 전 확인 후 체크해 주세요! (x 표시 해 주세요.)

- [x] Assignees(이슈 담당자)를 지정했습니다.
- [x] Labels, Milestone을 등록했습니다.
