### ISSUE TITLE
[FEAT] 응답 코드 세팅

### ISSUE THREAD

**Issue by wlshooo** [dnd-side-project/dnd-10th-3-backend#29]
## 요구사항
일관된 response 틀로 유연한 대처를 하기 위한 response setting

[요구사항_ID] 소분류명

## 상세 요구사항
ResponseCode, ResResult , ErrorCode 생성

## TODO

- [x] VERIFICATION_FAILED -> ErrorCode로 이동
- [x] 개발 팀 회의를 통해 사용하지 않기로 한 reponse code 삭제
- [x] "성공했습니다" 와 같은 일관된 메세지로 통일

## 예상 소요 시간

30분
## ✅ Issue 등록 전 확인 후 체크해 주세요! (x 표시 해 주세요.)

- [x] Assignees(이슈 담당자)를 지정했습니다.
- [x] Labels, Milestone을 등록했습니다.
