### ISSUE TITLE
[FIX] 스웨거 API 요청을 https로 변경

### ISSUE THREAD

**Issue by dlrjs2360** [dnd-side-project/dnd-10th-3-backend#35]
## 요구사항

[SYS-2-01] 백엔드 배포 환경 설정

## 상세 요구사항

배포버전 스웨거에서 api 요청 시 https로 현재 적용되어 있습니다. 이를 https로 호출하여 cors 에러가 발생하는 버그를 수정합니다.

## TODO

- [ ] Swagger Config 파일 수정
- [ ] 테스트

## 예상 소요 시간

3시간

## ✅ Issue 등록 전 확인 후 체크해 주세요! (x 표시 해 주세요.)

- [x] Assignees(이슈 담당자)를 지정했습니다.
- [x] Labels, Milestone을 등록했습니다.
