### ISSUE TITLE
[FEAT] 테스트 사전 질문 입력 추가 구현

### ISSUE THREAD

**Issue by dlrjs2360** [dnd-side-project/dnd-10th-3-backend#38]
## 요구사항

[TEST-3-01] 테스트 결과 조회

## 상세 요구사항

테스트 진행 시 사전 질문에 대한 입력값을 RequestDto에 추가합니다.

## TODO

- [ ] 나이, 성별에 대한 입력 필드를 추가

## 예상 소요 시간

1시간

## ✅ Issue 등록 전 확인 후 체크해 주세요! (x 표시 해 주세요.)

- [x] Assignees(이슈 담당자)를 지정했습니다.
- [x] Labels, Milestone을 등록했습니다.
