### ISSUE TITLE
[FEAT] 날짜 시간 형식 Timestamp로 변경

### ISSUE THREAD

**Issue by dlrjs2360** [dnd-side-project/dnd-10th-3-backend#39]
## 상세 요구사항

BaseEntity과 투표 ClosedAt 컬럼의 날짜 시간 형식을 Timestamp로 변경합니다.

## TODO

- [ ] 형식 변환 util 생성
- [ ] BaseEntity 형식 변경
- [ ] ClosedAt 형식 변경

## 예상 소요 시간

2시간

## ✅ Issue 등록 전 확인 후 체크해 주세요! (x 표시 해 주세요.)

- [x] Assignees(이슈 담당자)를 지정했습니다.
- [x] Labels, Milestone을 등록했습니다.
