### ISSUE TITLE
[FEAT] 투표 조회 API 구현

### ISSUE THREAD

**Issue by dlrjs2360** [dnd-side-project/dnd-10th-3-backend#4]
## 요구사항

[COMM-2-02] 투표 조회

## 상세 요구사항

- 투표에 연결된 선택지를 패치조인하여 함께 보여줘야 한다.
- 사용자가 해당 투표에 좋아요를 눌렀는지 확인할 수 있는 상태가 필요하다.
- 사용자가 해동 투표에 참여했는지 상태를 확인할 수 있어야 한다.
- 투표글 페이지에 방문할 때마다 조회수가 1 증가한다.
- 투표 마감 시간을 계산해서 제공해야 한다.

## TODO

- [ ] 선택지 패치조인
- [ ] 좋아요 스키마 연결
- [ ] 사용자별 좋아요 상태 조회 기능
- [ ] 사용자별 투표 상태 조회 기능
- [ ] 조회수 로직 (동기화)
- [ ] 마감 시간 계산 로직
- [ ] Swagger 명세서 작성
- [ ] Swagger 테스트 진행

## 예상 소요 시간

6시간

## ✅ Issue 등록 전 확인 후 체크해 주세요! (x 표시 해 주세요.)

- [x] Assignees(이슈 담당자)를 지정했습니다.
- [x] Labels, Milestone을 등록했습니다.
