### ISSUE TITLE
[FEAT] 결과 페이지 수정

### ISSUE THREAD

**Issue by dlrjs2360** [dnd-side-project/dnd-10th-3-backend#47]
## 상세 요구사항

결과 페이지에 사용자 설문조사 기능과 쿠킹 게시글을 추가합니다.

## TODO

- [ ] 사용자 설문조사 스키마 생성
- [ ] 정적 쿠킹 게시글 생성
- [ ] 테스트 

## 예상 소요 시간

3시간

## ✅ Issue 등록 전 확인 후 체크해 주세요! (x 표시 해 주세요.)

- [x] Assignees(이슈 담당자)를 지정했습니다.
- [x] Labels, Milestone을 등록했습니다.
