### ISSUE TITLE
[REFACTOR] 투표 리팩토링 

### ISSUE THREAD

**Issue by dlrjs2360** [dnd-side-project/dnd-10th-3-backend#52]
## 상세 요구사항

투표 카테고리, 이미지 등 리팩토링을 진행합니다.
카테고리 필드가 추가되고 이미지와 글을 함께 입력받습니다. 또한, 순서에 맞춰서 이미지를 입력합니다.

## TODO

- [x] 카테고리 추가
- [x] 이미지 null 처리 추가 구현
- [x] 유저 연결
- [ ] 테스트 주석처리

## ✅ Issue 등록 전 확인 후 체크해 주세요! (x 표시 해 주세요.)

- [x] Assignees(이슈 담당자)를 지정했습니다.
- [x] Labels, Milestone을 등록했습니다.
