### ISSUE TITLE
[FEAT] 투표 목록 조회 API 구현

### ISSUE THREAD

**Issue by dlrjs2360** [dnd-side-project/dnd-10th-3-backend#6]
## 요구사항

[COMM-2-01] 투표 목록 조회

## 상세 요구사항

- 투표마다 제목, 내용, 선택지가 모두 제공되어야 한다.
- 사용자별로 투표를 했는지에 대한 상태가 제공되어야 한다.
- 사용자별로 좋아요를 눌렀는지에 대한 상태가 제공되어야 한다.
- 투표 마감시간을 계산해 제공해야 한다.
- 페이지네이션을 통해 특정 단위로 끊어 제공해야 한다.

## TODO

- [ ] 페이지네이션
- [ ] 투표 상태 조회 기능
- [ ] 투표 시간 계산 기능
- [ ] Swagger 명세서 작성
- [ ] Swagger 테스트 진행

## 예상 소요 시간

8시간

## ✅ Issue 등록 전 확인 후 체크해 주세요! (x 표시 해 주세요.)

- [x] Assignees(이슈 담당자)를 지정했습니다.
- [x] Labels, Milestone을 등록했습니다.
