### ISSUE TITLE
[REFACTOR] 테스트 결과 API 수정

### ISSUE THREAD

**Issue by dlrjs2360** [dnd-side-project/dnd-10th-3-backend#63]
## 상세 요구사항

테스트 결과 페이지를 리팩토링합니다.

## TODO

- [x] 테스트 결과 페이지에 실제 이미지와 문구를 추가합니다.
- [x] #64
- [x] 데이터베이스에 저장된 테스트 ID 반환 로직 추가
- [x] Temperature에 맞는 데이터 수정 -> 실제 온도, 문구, 이미지 묶음

## 예상 소요 시간

6시간

## ✅ Issue 등록 전 확인 후 체크해 주세요! (x 표시 해 주세요.)

- [x] Assignees(이슈 담당자)를 지정했습니다.
- [x] Labels, Milestone을 등록했습니다.
