### ISSUE TITLE
[FEAT] 투표 필터링 API 구현

### ISSUE THREAD

**Issue by dlrjs2360** [dnd-side-project/dnd-10th-3-backend#8]
## 요구사항

[COMM-2-05] 투표 필터링 기능

## 상세 요구사항

- 특정 키워드(카테고리)로 원하는 투표들만 조회할 수 있어야 한다.

## TODO

- [ ] Swagger 명세서 작성
- [ ] Swagger 테스트

## 예상 소요 시간

2시간

## ✅ Issue 등록 전 확인 후 체크해 주세요! (x 표시 해 주세요.)

- [x] Assignees(이슈 담당자)를 지정했습니다.
- [x] Labels, Milestone을 등록했습니다.
