### ISSUE TITLE
[FEAT] 투표 검색 API 구현

### ISSUE THREAD

**Issue by dlrjs2360** [dnd-side-project/dnd-10th-3-backend#9]
## 요구사항

[COMM-2-06] 투표 검색 기능

## 상세 요구사항

- 검색 타겟은 제목, 본문 내용에 있는 키워드 중에 있어야 한다.
- 검색 내용은 페이지네이션이 적용되어야 한다.

## TODO

- [ ] 제목 본문 통합 검색 기능
- [ ] 페이지네이션
- [ ] Swagger 명세서 작성
- [ ] Swagger 테스트 진행

## 예상 소요 시간

6시간

## 기타 참고사항
- 선택지에 대한 키워드도 검색결과에 포함해야 할 지 고민중임.

## ✅ Issue 등록 전 확인 후 체크해 주세요! (x 표시 해 주세요.)

- [x] Assignees(이슈 담당자)를 지정했습니다.
- [x] Labels, Milestone을 등록했습니다.
